version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
    restart: unless-stopped
    env_file: ./src/.env
    environment:
      XDEBUG_REMOTE_HOST: "host.docker.internal"
      XDEBUG_IDE_KEY: "vscode.xdebug"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    volumes:
      - ./src:/app
    depends_on:
      - database
      - redis

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    environment:
      APP_DEBUG: 1
      SERVICE_UPSTREAM: app
    volumes:
      - ./src/public:/app/public
    depends_on:
      - app
    ports:
      - 8080:8080

  database:
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cronjob_dashboard
      MYSQL_USER: cronjob
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - database:/var/lib/mysql

  redis:
    image: redis:5-alpine
    restart: unless-stopped

volumes:
  database:
